version: '3.7'

networks:
  malmonet0:
   external: true    
    
services:
  malmocontrol0:    
    image: malmocontrol:latest    
    ports: 
      - "5002:5002"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./MalmoControl/appsettings.json:/home/MalmoControl/appsettings.json
    container_name: malmocontrol0
    networks: 
      malmonet0:
        aliases: 
          - malmocontrol    

  malmo-server0:    
    image: malmoserver:latest    
    ports:
      - "5900:5900"              
    depends_on:
      - malmocontrol0      
    container_name: malmo-server0
    volumes:
      - ./MalmoContainer/ConfigFolder/config.json:/home/malmo/MalmoPlatform/build/install/Python_Examples/ConfigFolder/config.json
    networks: 
      malmonet0:
        aliases: 
          - malmo-server
    environment:
     - MALMO_INSTANCE=0
  
  reference_agent0:
    image: reference_agent:latest
    container_name: reference_agent0
    networks: 
      malmonet0:
        aliases: 
          - reference_agent

  # pmengine0:
  #   image: "pmengine:latest"    
  #   container_name: pmengine0
  #   networks: 
  #     malmonet0:
  #       aliases: 
  #         - pmengine
  #   environment:
  #    - MQTT_BROKER_HOSTNAME=10.150.0.3
  #    - MQTT_BROKER_PORT=1883
  #    - MinecraftTopic=malmo/test/0

  accesscontrol0:
    image: "accesscontrol:latest"    
    container_name: accesscontrol0
    environment:
    - ASPNETCORE_URLS=https://+:5000
    - Kestrel__Certificates__Default__Path=cert-aspnetcore.pfx
    - Kestrel__Certificates__Default__Password=password
    - Logging:Console:LogLevel:Default=Information
    networks: 
      malmonet0:
        aliases: 
          - accesscontrol
   
  dashboardservice0:
    image: "dashboardservice:latest"
    container_name: dashboardservice0
    environment:
    - ASPNETCORE_URLS=https://+:5005
    - Kestrel__Certificates__Default__Path=cert-aspnetcore.pfx
    - Kestrel__Certificates__Default__Password=password
    - Logging:Console:LogLevel:Default=Information
    - ClientServerURL=https://localhost:9000/DashboardService/
    - authentication:IdentityServerBaseUrl=https://accesscontrol:5000
    - authentication:ClientIdentityServerBaseUrl=https://localhost:9000/AccessControl
    - authentication:IgnoreSSLErrors=true
    - MQTTSettings:Host=10.150.0.3
    - MQTTSettings:Port=1883
    networks: 
      malmonet0:
        aliases: 
          - dashboardservice
        
  nginx0:
    image: nginx:alpine
    container_name: nginx0
    depends_on: 
    # - pmengine0
    - accesscontrol0
    - dashboardservice0
    volumes:
    # -  ./PMEContainer/PerformanceDashboard:/usr/share/nginx/html/PerformanceDashboard
    # -  ./PMEContainer/MeasureConfig:/usr/share/nginx/html/measureconfig
    # -  ./PMEContainer/Workbench:/usr/share/nginx/html/workbench
    # -  ./PMEContainer/Diagnostics:/usr/share/nginx/html/diagnostics
    # -  ./PMEContainer/Settings/PerformanceDashboardSettings.json:/usr/share/nginx/html/PerformanceDashboard/assets/settings.json
    -  ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    -  ./Nginx/cert-aspnetcore.crt:/etc/nginx/cert-aspnetcore.crt
    -  ./Nginx/cert-aspnetcore.key:/etc/nginx/cert-aspnetcore.key
    -  ./Nginx/ssl_passwords.txt:/etc/nginx/ssl_passwords.txt
    ports:
    - "9000:443"    
    networks: 
      malmonet0:
        aliases: 
          - nginx
        
    
