http.host: 0.0.0.0
dead_letter_queue.enable: true
# read password from logstash.keystore
#xpack.monitoring.elasticsearch.username: logstash_system
#xpack.monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}
#xpack.monitoring.elasticsearch.url: https://elasticsearch:9200
#xpack.monitoring.elasticsearch.ssl.ca: /usr/share/logstash/config/certs/ca/ca.crt
