FROM python:3.8-slim-buster

RUN apt-get update
RUN apt-get install dos2unix
RUN apt-get -y install git

ARG CACHE_BREAKER

COPY ihmc-python-agent-helper-package /Tools/ihmc-python-agent-helper-package

COPY requirements.txt /
RUN pip3 install -r requirements.txt --upgrade

WORKDIR /app

COPY entrypoint.sh /app
RUN chmod 777 entrypoint.sh

COPY maps/ /app/maps

# copies src last to avoid re installing dependencies on every code change
COPY src/ /app/src

RUN dos2unix entrypoint.sh
CMD [ "sh","entrypoint.sh"]