from src.models.jags import asist_jags as aj
from src.models.jags.jag import Jag

victim_type = 'regular'
victim_id = 35
inputs_1 = {'victim-id': victim_id, 'victim-type': victim_type}
player_id_1 = 'red'

red_check_unlock = Jag(aj.CHECK_IF_UNLOCKED['urn'], None, inputs_1, None, 'abc-1111111')
red_drop = Jag(aj.DROP_OFF_VICTIM['urn'], None, inputs_1, None, 'red-drop-123')

print("Awareness test:")
print()

print(red_check_unlock.to_string())
print("is aware = " + str(red_check_unlock.is_aware(player_id_1)))
red_check_unlock.update_awareness(player_id_1, player_id_1, 1.0, 30400)
print(red_check_unlock.to_string())
print("is aware = " + str(red_check_unlock.is_aware(player_id_1)))
print(red_check_unlock.to_string())
print("is aware = " + str(red_check_unlock.is_aware(player_id_1)))
print("aware time = " + str(red_check_unlock.awareness_time(player_id_1)))
red_check_unlock.update_awareness(player_id_1, player_id_1, 0.0, 36000)
print(red_check_unlock.to_string())
print("is aware = " + str(red_check_unlock.is_aware(player_id_1)))
print("aware time = " + str(red_check_unlock.awareness_time(player_id_1)))
red_check_unlock.update_awareness(player_id_1, player_id_1, 1.0, 37000)
print(red_check_unlock.to_string())
print("is aware = " + str(red_check_unlock.is_aware(player_id_1)))
print("aware time = " + str(red_check_unlock.awareness_time(player_id_1)))

print()
print("Preparing Test")
print()

print(red_drop.to_string())
red_drop.update_awareness(player_id_1, player_id_1, 1.0, 30400)
red_drop.update_preparing(player_id_1, player_id_1, 1.0, 42000)
print(red_drop.to_string())
red_drop.update_preparing(player_id_1, player_id_1, 0.0, 44000)
print(red_drop.to_string())
red_drop.update_preparing(player_id_1, player_id_1, 0.0, 46000)
print(red_drop.to_string())
red_drop.update_preparing(player_id_1, player_id_1, 1.0, 48000)
print(red_drop.to_string())
red_drop.update_preparing(player_id_1, player_id_1, 0.5, 54000)
print(red_drop.to_string())
red_drop.update_preparing(player_id_1, player_id_1, 0.5, 56000)
print(red_drop.to_string())
red_drop.update_preparing(player_id_1, player_id_1, 0.0, 58000)
print(red_drop.to_string())

print()
print("Addressing Test")
print()

red_drop.update_addressing(player_id_1, player_id_1, 0.0, 58000)
print(red_drop.to_string())
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
red_drop.update_addressing(player_id_1, player_id_1, 0.0, 60000)
print(red_drop.to_string())
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
red_drop.update_addressing(player_id_1, player_id_1, 1.0, 65000)
print(red_drop.to_string())
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
red_drop.update_addressing(player_id_1, player_id_1, 0.5, 67500)
print(red_drop.to_string())
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
red_drop.update_addressing(player_id_1, player_id_1, 0.5, 69000)
print(red_drop.to_string())
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
red_drop.update_addressing(player_id_1, player_id_1, 0.0, 72000)
print(red_drop.to_string())
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))

print()
print("COMPLETION Test")
print()

red_drop.update_awareness(player_id_1, player_id_1, 1.0, 30400)
red_drop.update_preparing(player_id_1, player_id_1, 1.0, 42000)
print(red_drop.to_string())
print("is aware = " + str(red_drop.is_aware(player_id_1)))
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
print("is complete = " + str(red_drop.is_complete()))
red_drop.update_preparing(player_id_1, player_id_1, 0.0, 46000)
print(red_drop.to_string())
print("is aware = " + str(red_drop.is_aware(player_id_1)))
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
print("is complete = " + str(red_drop.is_complete()))
red_drop.update_addressing(player_id_1, player_id_1, 1.0, 46000)
print(red_drop.to_string())
print("is aware = " + str(red_drop.is_aware(player_id_1)))
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
print("is complete = " + str(red_drop.is_complete()))
red_drop.update_addressing(player_id_1, player_id_1, 0.0, 52000)
print(red_drop.to_string())
print("is aware = " + str(red_drop.is_aware(player_id_1)))
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
print("is complete = " + str(red_drop.is_complete()))
red_drop.update_completion_status(player_id_1, True, 52000)
print(red_drop.to_string())
print("is aware = " + str(red_drop.is_aware(player_id_1)))
print("is addressing = " + str(red_drop.is_addressing(player_id_1)))
print("is active = " + str(red_drop.is_active()))
print("is complete = " + str(red_drop.is_complete()))
