# -*- coding: utf-8 -*-
"""
.. module:: messages.agent
   :platform: Linux, Windows, OSX
   :synopsis: Module defining agent-generated message classes.

.. moduleauthor:: Dana Hughes <danahugh@andrew.cmu.edu>

Definition of message classes used by MinecraftBridge.  Classes in this module
are related to messages generated by agents, as opposed to the testbed.
"""