version: '3.7'

networks:
  asist_net:
   external: true    
    
services:
  asist_agent:
    image: "registry.gitlab.com/artificialsocialintelligence/study3/ac_cornell_ta2_asi-facework:0.0.3"
    container_name: "AC_CORNELL_TA2_ASI-FACEWORK"
    environment:
      - AGENT_NAME=AC_CORNELL_TA2_ASI-FACEWORK
      - AGENT_MAIN_RUN_FILE=faceworkAC.py
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ConfigFolder:/app/ConfigFolder    
    networks:
      asist_net:
        aliases:
          - "AC_CORNELL_TA2_ASI-FACEWORK"
