# -*- coding: utf-8 -*-
"""
  ~    __  ____                            ______  ________                          __      
  ~   /  |/  (_)___  ___  ______________ _/ __/ /_/ ____/ /__  ____ ___  ___  ____  / /______
  ~  / /|_/ / / __ \/ _ \/ ___/ ___/ __ `/ /_/ __/ __/ / / _ \/ __ `__ \/ _ \/ __ \/ __/ ___/
  ~ / /  / / / / / /  __/ /__/ /  / /_/ / __/ /_/ /___/ /  __/ / / / / /  __/ / / / /_(__  ) 
  ~/_/  /_/_/_/ /_/\___/\___/_/   \__,_/_/  \__/_____/_/\___/_/ /_/ /_/\___/_/ /_/\__/____/  
                                                       

.. module:: MinecraftElements
    :platform: Linux, Windows, OSX
    :synopsis: A set of enumerations of elements used in Minecraft
.. moduleauthor:: Dana Hughes <danahugh@andrew.cmu.edu>


The MinecraftElements package provides a set of int enumerations of common
Minecraft elements---blocks, entities, properties, etc.  The enumerations
allows for specific Minecraft concepts to be represented as an integer, string,
or enumerated object, as well as ensuring common representation between
projects, and avoiding subtle bugs generated by using incorrect numerical
values or misspelled string.

Example Usage
-------------

MinecraftElement enumerations can be instantiated in several ways:
  
1.  As an explicit enumeration::

    >>> block = MinecraftElements.Block.clay

2.  From strings::

    >>> block = MinecraftElements.Block['clay']

3.  From integer values::

    >>> block = MinecraftElements.Block(82)


Conversely, an instance of the enumeration can be readily converted to the
integer or string representation

1.  To integer::

        >>> blockInt = block.value

2.  To string::

        >>> blockStr = block.name

3.  enumerations can be used in place of integer values, such as in a numpy array::

        >>> import numpy as np
        >>> blockArray = np.array([MinecraftElements.Block.Clay, 
                                   MinecraftElements.Block.dirt], dtype=np.uint16)


The available values of an enumeration can be determined by converting the
enumeration to a list (or other collection)::

    >>> enumMembers = list(MinecraftElements.Block)
"""

__all__ = ["Block", "Color", "Entity", "Facing", "Flower", "Half", "Hinge", "Item", "MonsterEgg", "Shape", "Stone", "Wood"]

__author__ = "Dana Hughes"
__email__ = "danahugh@andrew.cmu.edu"
__url__ = "https://gitlab.com/cmu_asist/MinecraftElements"
__version__ = "0.4.5"


from .blocks import Block
from .colors import Color
from .entities import Entity
from .facing import Facing
from .flowers import Flower
from .halfs import Half
from .hinge import Hinge
from .items import Item
from .monster_eggs import MonsterEgg
from .shapes import Shape
from .stones import Stone
from .woods import Wood
from .marker_blocks import MarkerBlock
