# -*- coding: utf-8 -*-
"""
.. module:: beep_event
   :platform: Linux, Windows, OSX
   :synopsis: Message class encapsulating Beep Events

.. moduleauthor:: Dana Hughes <danahugh@andrew.cmu.edu>

Definition of a class encapsulating Beep Event messages.
"""

import json
import sys
from .message_exceptions import (
    MalformedMessageCreationException, 
    MissingMessageArgumentException, 
    ImmutableAttributeException
)
from .base_message import BaseMessage


class BeepEvent(BaseMessage):
    """
    A class encapsulating Beep Event messages.

    Note
    ----
    Constructing a BeepEvent message requires passing the following keyword
    arguments:

        `sourceEntity`
        `message`
        `location`

    While aliases exist for these attributes, they are currently not accepted
    as constructor parameters.

    Attributes
    ----------
    sourceEntity : string
        The name of the entity triggering the beep event
    source_entity : string
        An alias for `sourceEntity`
    message : string
        The message emitted by the source entity
    location : tuple of floats
        The (x,y,z) of the location of the entity
    beep_x : float
        The x location of the entity, alias of location[0]
    beep_y : float
        The y location of the entity, alias of location[1]
    beep_z : float
        The z location of the entity, alias of location[2]
    """


    def __init__(self, **kwargs):
        """
        BeepEvent messages are constructed from the listed keyword arguments.
        Multiple keywords can be used to define the message attributes; 
        keywords are listed in the order that they are checked

        Keyword Arguments
        -----------------
        source_entity : string
        sourceEntity : string
            Name of the entity triggering the beep
        message : string
            Message emitted by the source entity
        location : tuple of ints
        beep_x : int
        beep_y : int
        beep_z : int
            Location (x,y,z) of the entity.  If `location` is not provided,
            uses (`beep_x`, `beep_y`, `beep_z`)
        """

        BaseMessage.__init__(self, **kwargs)


        # Get the location of the entity: try `location` first, followed by
        # `beep_x`, `beep_y`, `beep_z`
        location = kwargs.get('location', None)

        if location is None:
            try:
                location = (kwargs['beep_x'], kwargs['beep_y'], kwargs['beep_z'])
            except KeyError:
                raise MissingMessageArgumentException(str(self),
                                                      'location') from None

        # Location needs to be able to be coerced into a tuple of ints.  Raise 
        # an exception if not possible
        try:
            self._location = tuple([float(x) for x in location][:3])
        except:
            raise MalformedMessageCreationException(str(self), 'location', 
                                                    location) from None

        # Get the source entity; raise an exception if not present
        self._sourceEntity = kwargs.get('source_entity', 
                             kwargs.get('sourceEntity', None))
        if self._sourceEntity is None:
            raise MissingMessageArgumentException(str(self), 
                                                  'source_entity') from None

        # Get the message; raise an exception if not present
        try:
            self._message = kwargs['message']
        except KeyError:
            raise MissingMessageArgumentException(str(self), 
                                                  'message') from None


    def __str__(self):
        """
        String representation of the message.

        Returns
        -------
        string
            Class name of the message (i.e., 'BeepEvent')
        """

        return self.__class__.__name__


    @property
    def sourceEntity(self):
        """
        Get the name of the entity that produced the beep message.  Attempting 
        to set the value of the `sourceEntity` will result in an 
        `ImmutableAttributeException` being raised.        
        """

        return self._sourceEntity

    @sourceEntity.setter
    def sourceEntity(self, entity):
        raise ImmutableAttributeException(str(self), "sourceEntity") from None


    @property
    def source_entity(self):
        """
        Alias for `sourceEntity`.
        """
        return self._sourceEntity

    @source_entity.setter
    def source_entity(self, entity):
        raise ImmutableAttributeException(str(self), "source_entity") from None


    @property
    def message(self):
        """
        Get the message generated by the beep device.  Attempting to set the
        value of `message` will result in an `ImmutableAttributeException`
        being raised.
        """

        return self._message

    @message.setter
    def message(self, message):
        raise ImmutableAttributeException(str(self), "message") from None


    @property
    def location(self):
        """
        Get the location of the entity when the beep message was generated.
        Attempting to set the value of `location` will result in an
        `ImmutableAttributeException` being raised.
        """

        return self._location

    @location.setter
    def location(self, location):
        raise ImmutableAttributeException(str(self), "location") from None


    @property
    def beep_x(self):
        """
        Get the x-value of the location of the entity when the beep message was
        generated (i.e., `location[0]`).  Attempting to set the x-value of the
        location will result in an `ImmutableAttributeException` being raised.
        """

        return self._location[0]

    @beep_x.setter
    def beep_x(self, x):
        raise ImmutableAttributeException(str(self), "beep_x") from None
    

    @property
    def beep_y(self):
        """
        Get the y-value of the location of the entity when the beep message was
        generated (i.e., `location[1]`).  Attempting to set the y-value of the
        location will result in an `ImmutableAttributeException` being raised.
        """

        return self._location[1]

    @beep_y.setter
    def beep_y(self, y):
        raise ImmutableAttributeException(str(self), "beep_y") from None


    @property
    def beep_z(self):
        """
        Get the z-value of the location of the entity when the beep message was
        generated (i.e., `location[2]`).  Attempting to set the z-value of the
        location will result in an `ImmutableAttributeException` being raised.
        """

        return self._location[2]

    @beep_z.setter
    def beep_z(self, z):
        raise ImmutableAttributeException(str(self), "beep_z") from None



    def toDict(self):
        """
        Generates a dictionary representation of the BeepEvent message.  
        BeepEvent information is contained in a dictionary under the key "data".
        Additional named headers may also be present.

        Returns
        -------
        dict
            A dictionary representation of the BeepEvent.
        """

        jsonDict = BaseMessage.toDict(self)

        # Check to see if a "data" is in the dictionary, and add if not
        # Note that headers should have been added in jsonDict, as well as
        # common message data.
        if not "data" in jsonDict:
            jsonDict["data"] = {}

        # Add the beep event data
        jsonDict["data"]["source_entity"] = self.sourceEntity
        jsonDict["data"]["message"] = self.message
        jsonDict["data"]["beep_x"] = self.beep_x
        jsonDict["data"]["beep_y"] = self.beep_y
        jsonDict["data"]["beep_z"] = self.beep_z

        return jsonDict


    def toJson(self):
        """
        Generates a JSON representation of the BeepEvent message.  BeepEvent
        information is contained in a JSON object under the key "data".
        Additional named headers may also be present.

        Returns
        -------
        string
            A JSON string mapping header names to a JSON representation of the
            BeepEvent message.
        """

        return json.dumps(self.toDict())
