# -*- coding: utf-8 -*-
"""
.. module:: messages.analytic_components
   :platform: Linux, Windows, OSX
   :synopsis: Module defining message classes generated by analytic components.

.. moduleauthor:: Dana Hughes <danahugh@andrew.cmu.edu>

Definition of message classes used by MinecraftBridge.  Classes in this module
are related to messages generated by analytic components.
"""